[package]
name = "p"
version = "0.0.6"
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
clap_complete = "4.1.2"
colored = "2.0.0"
dirs = "4.0.0"
serde = { version = "1.0.152", features = ["derive"] }
shellexpand = "3.0.0"
simsearch = "0.2.4"
toml = "0.7.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
