# Build and upload the rust binary to GitHub releases
name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            target/x86_64-apple-darwin/release/p
            target/aarch64-apple-darwin/release/p
            target/x86_64-pc-windows-msvc/release/p.exe
            target/x86_64-unknown-linux-gnu/release/p

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release
      - uses: softprops/action-gh-release@v1
        with:
          files: p
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write